# Generated by Django 3.0.5 on 2020-04-22 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quote',
            name='item',
            field=models.ManyToManyField(blank=True, to='core.QuoteItem'),
        ),
    ]
