# Generated by Django 3.0.5 on 2020-05-02 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20200501_1116'),
    ]

    operations = [
        migrations.AddField(
            model_name='quoteitem',
            name='quote_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
