# Generated by Django 3.0.5 on 2020-05-15 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_quoteitem_quote_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='notes',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='quote',
            name='notes',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
    ]
