# Generated by Django 3.0.5 on 2020-05-15 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20200515_0939'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quote',
            name='notes',
            field=models.CharField(max_length=2000, null=True),
        ),
    ]
