# Generated by Django 3.0.5 on 2020-05-17 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20200515_1512'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='notes',
            field=models.CharField(default='Test Note', max_length=2000),
            preserve_default=False,
        ),
    ]
